# Generated by Django 2.2.4 on 2019-11-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='student',
            new_name='user',
        ),
    ]
